### PR TITLE
Template installs deps using main branch

### LINKED ISSUE #1015: Error installing basic template
Looks like it's going after a branch named master that doesn't exist, the branch is named main:

```
 Rubygems    Adding Thin into Gemfile...
--------------------------------------------------------------------------------

     gemfile    thin
     gemfile    mocha
     gemfile    rails-controller-testing
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile

    Rubygems    Adding Elasticsearch libraries into Gemfile...
--------------------------------------------------------------------------------

     gemfile    elasticsearch
     gemfile    https://github.com/elasticsearch/elasticsearch-rails.git
     gemfile    https://github.com/elasticsearch/elasticsearch-rails.git
         run    git add Gemfile* from "."
         run    git commit -m 'Added libraries into Gemfile' from "."
[master b3d0011] Added libraries into Gemfile
 1 file changed, 7 insertions(+), 1 deletion(-)

 Application    Disabling asset logging in development...
--------------------------------------------------------------------------------

         run    git add config/ from "."
         run    git commit -m 'Disabled asset logging in development' from "."
[master 0c25ea6] Disabled asset logging in development
 1 file changed, 2 insertions(+)

    Rubygems    Installing Rubygems...
--------------------------------------------------------------------------------

         run    bundle install from "."
Fetching https://github.com/elasticsearch/elasticsearch-rails.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify master` in directory /home/jason/Workspace/searchapp has failed.
Revision master does not exist in the repository https://github.com/elasticsearch/elasticsearch-rails.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory
'/home/jason/.rvm/gems/ruby-2.7.3@hearingtracker/cache/bundler/git/elasticsearch-rails-60da80899bf51572b681abf96e88fe8b6c0727b4'
```

### PR DESCRIPTION
**Pull request by tabuchid**
bundle install was failing in the basic template.
This adds branch main to fix the issue.
Fixes #1015

### CODE REVIEW

**Comment by rodricios** [comment]
Bump!

**Review by rodricios — APPROVED** [review]

**Comment by tabuchid** [comment]
Anything I need to do here?

**Comment by tabuchid** [comment]
Bump

**Comment by picandocodigo** [comment]
I *think* this shouldn't be an issue using a newer version of Bundler, but I'll merge anyway to be more explicit with the branch. Thanks for your contribution @tabuchid!

**Comment by tabuchid** [comment]
Ah good to know and thank you!

**Pull request merged**
