### PR TITLE
explicitely -> explicity in README

### PR DESCRIPTION
**Pull request by radar**
Just a small typo fix.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
:+1:

**Comment by mogox** [comment]
Looks good!  Hey @radar have you signed the contributor license agreement? https://www.elastic.co/contributor-agreement/ 

Anything else missing @karmi?

**Comment by radar** [comment]
Signed the CLA>

**Comment by karmi** [comment]
Many thanks for catching that and also for signing the CLA!

**Pull request closed without merging**
