### PR TITLE
[MODEL] Add pipeline to import

### PR DESCRIPTION
**Pull request by kellyjosephprice**
This adds the pipeline option to the bulk call of importing.

### CODE REVIEW

**Comment by picandocodigo** [comment]
Thanks for bringing this up @kwerle, I'm going to take a look into this as soon as possible.

**Comment by kwerle** [comment]
@picandocodigo 
How's it looking?  Anything I can do to help?

**Comment by picandocodigo** [comment]
The PR looks good. @kellyjosephprice, would you mind rebasing your branch with master? We'll look into releasing a new version of the gem next week. Thank you!

**Comment by kellyjosephprice** [comment]
@picandocodigo Thanks for looking at this. I rebased, but it looks like travis may have stalled.

**Comment by picandocodigo** [comment]
@kellyjosephprice That's great, thanks!

Travis has been like this all day for me. It takes ages, but eventually it runs the build. I'll keep an eye on it!

**Pull request merged**
