### PR TITLE
[MODEL] Add "suggest" method to get response suggest

### PR DESCRIPTION
**Pull request by nipe0324**
I would like to use suggest of Elasticsearch response.
But `Elasticsearch::Model::Response::Response` class hasn't the method. That's why I added it.

I have already signed the CLA.

### CODE REVIEW

**Comment by karmi** [comment]
I think it makes sense. Can we also have integration tests for the feature, and update to the [example application HTML template](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/index.html.dsl.erb#L50) (in a separate commit?)

**Comment by karmi** [comment]
Some tests on Travis are [failing](https://travis-ci.org/elastic/elasticsearch-rails/builds/87294328), do they run locally for you?

**Comment by nipe0324** [comment]
I fixed it.

**Comment by karmi** [comment]
I'm sorry for such a long delay, I've tweaked the code a bit and merged it! Thanks!

**Pull request closed without merging**
