### PR TITLE
Do not reinvent Enumerable#each_slice

### PR DESCRIPTION
**Pull request by lompy**
Just spotted good use case for Enumerable#each_slice

### CODE REVIEW

**Comment by karmi** [comment]
@lompy Nice!! Can you sign the CLA so I can merge it?

**Comment by lompy** [comment]
Sorry, I don't know what CLA means and what it means to sign it.

**Comment by karmi** [comment]
@lompy Sorry for brevity, it's described in the [contributing guidelines](https://github.com/elastic/elasticsearch-rails/blob/master/CONTRIBUTING.md), the target link is https://www.elastic.co/contributor-agreement/?license=icla

**Comment by lompy** [comment]
@karmi Signed it providing my github name, but CLA check still fails

**Comment by karmi** [comment]
@lompy It's not auto-updating (something we might add in the future), but I can see the signature as verified now, thanks!

**Comment by karmi** [comment]
Thanks!, merged!

**Comment by lompy** [comment]
No proplem! Next time I'll try to read contributing guidelines

**Pull request closed without merging**
