### PR TITLE
adds to documentation around importing

### PR DESCRIPTION
**Pull request by meesterdude**
I ran into some slow indexing with my app and found the vanilla way of importing to be too slow, but didn't see any mention of alternatives in the documentation. I later see #54 as a possible solution, only after reaching a similar conclusion through my own muddling about. I figured it made sense for the documentation to expand upon this, and save future users the same trouble. I pondered if maybe there was a better way to import out of the box too -- or maybe improve the `import` method; but this seemed like a simpler step.

### CODE REVIEW

**Comment by karmi** [comment]
Hi Russel, apologies for the ridiculous delay. As much as I like long READMEs, I wouldn't like it to blow up beyond reason, and I think this doesn't fit with it.

I see two options:

1. Creating a Wiki page at Github with something like "Tips and Tricks for Importing"
2. Moving the content there
3. When you say "use batching and threads/forks", it's music to my ears, but I'd like to see a _working_ example for that -- otherwise it's just handwaving on our part, leaving the user with the implementation as homework. What do you think?

**Comment by meesterdude** [comment]
@karmi no trouble. I have no trouble with a wiki page for it, but I don't think the wiki is enabled? I don't see it in the sidebar. 

I like factory_girls https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md over what devise has https://github.com/plataformatec/devise/wiki

**Comment by karmi** [comment]
Hi, true -- I've enabled Wiki just now. In this case, I think we're shooting for a separate page, with specific, detailed information about importing, so what we need is that page + a Home page with only the link?

**Comment by meesterdude** [comment]
I was thinking of creating an "all things indexing" so this can go there, along with a tip about refreshing the index which i think is missing from the docs too; i found it in a github issue. 

So, in that light there's a page for each major topic, and everything can fall under those in some sense. versus many wiki pages of varying relevance and quality. That would be my approach to it, what do you think? 

otherwise, yes I was going to give code examples and explain how to optimize and improve.

**Comment by karmi** [comment]
Hi, undecided, I think that "many wiki pages on specific topics" make usually more sense than trying to come up with a "big chapter" upfront... I'd start with that specific topic on importing, and see where it leads..

**Comment by karmi** [comment]
@meesterdude Closing this, if it's fine, let's work on that Wiki page? Can you please open an issue to communicate when you have something ready?

**Pull request closed without merging**
