### PR TITLE
required json for end of issue #313

### PR DESCRIPTION
**Pull request by tostasqb**

### CODE REVIEW

**Comment by psylone** [comment]
Same as #728 PR.

**Comment by psylone** [comment]
Since this change doesn't affect the test suit, can it be merged?

**Comment by nilbus** [comment]
BTW, as harmless as this PR would be, I couldn't reproduce this problem with rails 3.2, 4.2, 5.0, or 5.1 on MRI and JRuby. I imagine `rails new` is requiring the json library before this template script is executed. Clearly others are experiencing this problem though, and I wonder if some combination of dependencies is causing it.

**Comment by tostasqb** [comment]
Signed the licence agreement

**Comment by estolfo** [comment]
I can't reproduce this but if there's an error for someone, I don't see a problem with requiring `json`.

**Pull request closed without merging**
