### PR TITLE
Updated README.MD

### PR DESCRIPTION
**Pull request by anandvc**
Include the step to create the index for the model that we'll import.

### CODE REVIEW

**Comment by estolfo** [comment]
Let's keep the example simple and not include this for now.

**Comment by anandvc** [comment]
@estolfo Does the example work for you without that line which creates the index?

**Comment by estolfo** [comment]
I was hoping to keep the example as simple as possible and index creation doesn't always happen at the same time as import jobs. Is it really unclear without the `create_index!` line?

**Comment by anandvc** [comment]
@estolfo Yes. The Readme does not mention index creation at all, but it is necessary for the example to work. If you want, we can add a comment for the create_index! line to say that this can be done asynchronously.

**Comment by estolfo** [comment]
@anandvc I think a comment would be better, so index creation right at import time wouldn't be encouraged. I think that operation would usually be done at another point.
I'll reopen the issue if you want to update the PR?

**Comment by anandvc** [comment]
Thanks, @estolfo! I've updated the PR and added a comment.

**Comment by estolfo** [comment]
thanks!

**Pull request merged**
