### PR TITLE
reindex on assoc updates only if already saved

### PR DESCRIPTION
**Pull request by Meekohi**
Only trigger a re-index if the Article has already been saved. This is important is you ever create an object with `.new` instead of `.create` and then add associations to it _before_ saving (note that rails is smart and will "wait" to do all the database work on `.save` in this case).

### CODE REVIEW

**Comment by karmi** [comment]
Hi, that sounds legitimate -- although, would you have an example Ruby code to demonstrate how it breaks without the condition? I'd like to see it not only to satisfy my curiosity, but to better understand the flow there.

**Comment by Meekohi** [comment]
So, I believe the following would exercise the error (based on the example in `examples/activerecord_associations.rb`)

```
category = Category.create title: 'One'
author = Author.create first_name: 'John', last_name: 'Smith', department: 'Business'

article  = Article.new title: 'First Article'
article.categories << category
```
```
article.authors << author
article.save!
```

**Comment by karmi** [comment]
Right, thanks for pointing it out, I can see it in Pry now!

We definitely need to fix that example, I'd like to consider another way of expressing the intention there, however: instead of using `if a.id`, what if we used `if a.persisted?` That seems to me to convey the intention better, ie. _Save the document when the database record has been already stored_, as opposed to _Save the document when the database record has an ID_.

I can imagine scenarios where the latter approach would make sense, eg. when you're setting the IDs yourself in application code, but in the context of the example, which relies on the database-generated ID, the `persisted?` approach is more didactic?

**Comment by Meekohi** [comment]
Yup makes sense -- wanting to push to elasticsearch with an id but before saving would be an odd use case, and now this example makes it pretty clear that you need consider the details of when you do/don't index the Article anyway.

**Pull request closed without merging**
