### PR TITLE
[MODEL] Automatic index configuration using .yml or .json files

### PR DESCRIPTION
**Pull request by dabit**
With this patch, the `elasticsearch-model` gem will search for .yml or .json files named after the `document_type` of every class and load it into `@settings` and `@mappings` accordingly.

From README:

#### Configuration files

Elasticseach-model will automatically load settings and mappings included in
a .yml or .json file named after the `document_type` that exists in
`config/elasticsearch` for any specific class.

```yml
# In: config/elasticsearch/article.yml
#
settings:
  number_of_shards: 7
  analyzer:
    my-analyzer:
      tokenizer: "whitespace"
mappings:
  article:
    properties:
      name:
        analyzer: "my-analyzer"
```
```ruby
Article.settings
# => {"number_of_shards"=>7, "analyzer"=>{"my-analyzer"=>{"tokenizer"=>"whitespace"}}}

Article.mappings
# => {"article"=>{"properties"=>{"name"=>{"analyzer"=>"my-analyzer"}}}}
```

### CODE REVIEW

**Comment by chrisdebruin** [comment]
+1

**Comment by dabit** [comment]
Hey @karmi,

Hope you had a great vacation, just a friendly reminder of these changes.

**Comment by karmi** [comment]
@dabit Sorry for the long delay! I got stalled with stuff after the return.

I'm not entirely sold on the "convention over configuration" approach in this case, I must say... I like the original approach much more... This also makes it dependent on Rails' `config` folder. What do you think about returning to the original approach?

**Comment by dabit** [comment]
@karmi ok, I really am inclined to the Rails way but I also see your point. Allow me to make the changes on the other approach (#346) and then you decide what to merge.

Thanks!

**Comment by karmi** [comment]
Hi @dabit, I still like the initial approach in #346 more, sorry :) I'm just pinging here that I think it's a great feature -- there's no time pressure, though, so please ping me when you have something new!

**Comment by dabit** [comment]
@karmi Hey! Haven't forgotten, just that things got a little crazy at work for the last couple of weeks. I'm pretty sure I'll have time to improve #346 within the next week or so. Sorry about the radio silence.

**Comment by karmi** [comment]
Closed via 5c7cd1239976d2e9d2c51a852800412f3454d9fe

**Pull request closed without merging**
