### PR TITLE
[#966] Add alias for Elasticsearch::Model::Response::Results#records

### PR DESCRIPTION
**Pull request by NoharaMasato**
Quick Fix for #966

### CODE REVIEW

**Comment by NoharaMasato** [comment]
I signed the agreement.

**Comment by picandocodigo** [comment]
Hi @NoharaMasato,
Thank you for your contribution! Could you add some a test please?

**Comment by NoharaMasato** [comment]
@picandocodigo 
Thank you for checking.
I added some tests!

**Comment by picandocodigo** [comment]
Thank you @NoharaMasato! I merged this [here](https://github.com/elastic/elasticsearch-rails/pull/1000), and it'll be available on the next release :+1:

**Pull request closed without merging**
