### PR TITLE
[Model] Fix ActiveRecord sorted collection

### PR DESCRIPTION
**Pull request by inkstak**
This is a fix for #608.
It also introduces tests against ActiveRecord 5.0.

The fix about sorted records is cover by a test, but there are still 10 errors on other subjects when running tests with AR 5.
I'didn't run unit tests as they are already failing.

### CODE REVIEW

**Comment by nickrivadeneira** [comment]
@inkstak You'll need to sign the contributor agreement: https://www.elastic.co/contributor-agreement

Would love for this to be merged in.

**Comment by sfcgeorge** [comment]
Confirm this fix works for me, without it result order is all over the place. Had to monkeypatch it in as Rails 5 has been out long enough.

**Comment by connorshea** [comment]
@nickrivadeneira any updates on this?

**Comment by nickrivadeneira** [comment]
@connorshea I'm not a elasticsearch member unfortunately, I was just making sure that instak signed the agreement so this could be merged in when the elasticsearch team looks at it. This repo seems to be dead though :( The person we need is @karmi

**Comment by inkstak** [comment]
I confirm I signed the agreement. The github check is not up to date.

**Comment by karmi** [comment]
@inkstak, you were correct, the check has indeed been out of sync -- it's corrected now.

@nickrivadeneira, it's not dead, I just have a hard time keeping up with all the gems across the two repos. I'll pull the patch and verify locally and merge.

**Comment by nickrivadeneira** [comment]
@karmi Makes sense. Thanks for looking into this one

**Comment by karmi** [comment]
Hi, I've merged the patch into `master`, many thanks for that, and apologies again for the delay. I'm not sure when I'll get to a release, but if you want a patch release with the change, I can do it anytime.

(So, one reason why processing PRs is not a simple "pull, run tests, rewrite commit message, push" is that I needed fix [all this](https://github.com/elastic/elasticsearch-rails/compare/94d0b28...master) while doing the pull, so the tests are green and we can add more patches on top of the branch without fear...)

**Comment by inkstak** [comment]
Thanks 👍

**Pull request closed without merging**
