### PR TITLE
@ids is not an instance variable set anywhere

### PR DESCRIPTION
**Pull request by tpitale**
But, there is a method called `ids` which collections the ids from hits: https://github.com/elasticsearch/elasticsearch-rails/blob/104f91f24ba8d3dc7629b0eaf058329dc2cdc08c/elasticsearch-model/lib/elasticsearch/model/response/records.rb#L33

### CODE REVIEW

**Comment by karmi** [comment]
Hey @tpitale, blast from the past! :) You're right, the `@ids` maybe worked at certain point in DM, but it doesn't anymore. Can you please [sign the CLA](https://github.com/elastic/elasticsearch-rails/blob/master/CONTRIBUTING.md) so I can merge the patch?

(I understand this is a tiny change, but it's way easier for us to ask for the signature even for these... Thanks for understanding!)

**Comment by tpitale** [comment]
I'll sign as soon as I'm back in the States. Doesn't seem to work on mobile right now (just says preview not available). I should be back the end of next week.

**Comment by karmi** [comment]
@tpitale Cool! Take your time and thanks! (Yeah, I think the service works correctly only on a computer...)

**Comment by tpitale** [comment]
Signed!

**Comment by tpitale** [comment]
I just re-signed the CLA. But the checks don't seem to update.

**Pull request closed without merging**
