### PR TITLE
Compatibility with active record 3.0 and 3.1

### PR DESCRIPTION
**Pull request by sobrinho**
Calling `super()` makes the active record adapter compatible with older versions of active record.

### CODE REVIEW

**Comment by dre-hh** [comment]
@karmi we've got rails 4.2 by the time now. I've personally upgraded some rails projects from 3.0 to 3.2. I don't remember wether there was some minor incompatibilities in AR. The whole process was actually pretty painless. I suggest we close this issue and encourage people to upgrade at least to AR 3.2

**Comment by karmi** [comment]
@dre-hh Agreed that Rails 3.0 is a legacy thing now, however, the gem works with that version, so I'm not sure if we should remove it... On the other hand, I'm all for adding support or 3.2.x and getting rid of 3.0.x _if it would complicate things_.

**Comment by sobrinho** [comment]
Closing, we finally upgraded the project, thanks!

**Comment by karmi** [comment]
@sobrinho, that's the best outcome! :) Best of luck!

**Pull request closed without merging**
