### PR TITLE
Included missing import functionality on Mongoid adapter

### PR DESCRIPTION
**Pull request by fabiob**
I was trying to use the `import` funcionality on Mongoid today, and I noticed it didn't had the same funcionality as running it with ActiveRecord.

### CODE REVIEW

**Comment by karmi** [comment]
@fabiob Thanks! However, we need an integration test for the change, similar to eg. https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/test/integration/active_record_import_test.rb

Can you add that? Also, can you sign the CLA so I can merge the patch?

**Comment by karmi** [comment]
A duplicate of #295, maybe get in touch with the author and somehow merge the patches?

**Comment by karmi** [comment]
(I can help with the Git side of things, eg. preserving the author of a particular commit etc)

**Comment by fabiob** [comment]
OK, I signed the CLA.

I just checked @hallelujah's PR (#295): it looks way better than mine, and includes the integration tests. I guess I'll just drop my PR, merge his work with the master and work on the issues you commented.

**Pull request closed without merging**
