### PR TITLE
7.0 support

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
If I use ES 6.x should I use es-rails 7.x?

**Comment by estolfo** [comment]
Hi @PikachuEXE Does this answer your question? https://github.com/elastic/elasticsearch-rails#compatibility
The 7.x gem version is intended to support ES 7.x.
The 6.x gem version is intended to support ES 6.x.

**Comment by PikachuEXE** [comment]
Will lock es-rails at 6.x until we are able to upgrade ES to 7.x

**Comment by cdenneen** [comment]
Shouldn't there be a 7.x branch to match the previous releases?

**Comment by picandocodigo** [comment]
@cdenneen I've been working with `7.x` in master so far. Once I start working towards `8.0`, it'll make sense to open a `7.x` branch and continue working there. Right now I'm a bit behind on that work.

**Pull request merged**
