### PR TITLE
Allow ES 6.0, Remove Rails 3.x 4.0 and 4.1 (EOL)

### PR DESCRIPTION
**Pull request by leifcr**
This PR does the following:
1) Allows ES 6.0
2) Removes Rails 3.x, 4.0 and 4.1, since they are all eol.

There is some work to be done on rewriting the tests for ES 6.0, as one fail due to multiple mappings removal in ES 6.0.

Please advice on what needs to be done in order to fix the tests for ES 6.0

This is related to #763, #756, #801

The parent-child relation tests, needs to be rewritten to join mapping.

### CODE REVIEW

**Comment by leifcr** [comment]
As ES 6.0 deprecated _parent, the tests for child-parent needs to be rewritten for join. Suggestions welcome.

**Comment by estolfo** [comment]
Hi @leifcr 
Thanks for your pull request!
I work at Elastic on the Ruby team and while Ruby 2.2.x is EOL'ed, there's nothing holding us back from supporting it. The same is true of Rails 3.x.
With that said, would you mind adding those tests back to your PR? As for #to_ary to work on Ruby 2.2.x, you can stub the methods as I've done in this PR.
Thanks!
Emily

**Comment by estolfo** [comment]
Hi @leifcr 
Is there any chance you saw my comment above?
Thanks

**Comment by leifcr** [comment]
@estolfo I'll rebase against master and add 2.2 + rails 3.x tests again.

**Comment by estolfo** [comment]
Hi @leifcr 

Thank you very much for your work on this but do you mind if we close the pull request? I've created a 6.x branch and updated the travis matrices in the 6.x and 5.x branches. Master will be for 7.0 support.
I've also [updated the parent-child relation tests](https://github.com/elastic/elasticsearch-rails/commit/6cc201e3e3cb8705f7270183d80d4ba7ee7d6bff#diff-0279f754e070049ddfadf23fe9af9f52) for the deprecation of multiple types in a single index on Elasticsearch 6.x.

Please let me know if you would be ok with me closing this in favor of the latest changes to the repo.
Thanks again!
Emily

**Comment by leifcr** [comment]
Please close the PR in favor of the other changes! Looking forward to the
6.x branch

Thanks!

2018-06-28 18:07 GMT+02:00 Emily S <notifications@github.com>:

**Comment by estolfo** [comment]
thanks @leifcr !

**Pull request closed without merging**
