### PR TITLE
[WIP] Convert from Virtus to ActiveAttr

### PR DESCRIPTION
**Pull request by ryansch**
I've had so many issues with the way Virtus decides to do things that I finally gave up and ripped it out in favor of ActiveAttr.

### CODE REVIEW

**Comment by ryansch** [comment]
This has changes from 2 of my other branches rolled into it.  If there's interest in going in this direction I'll strip them out or close the other PRs.

**Comment by karmi** [comment]
@ryansch I like the idea itself -- many people seem to have performance and other issues with Virtus. 

What I'm thinking though, is that it would be best to make this support _pluggable_, in the spirit of "adapters" we have in `elasticsearch-model` for ActiveRecord, Mongoid, etc etc etc. 

My reasoning would not be of academical, but of practical nature: so we rip out Virtus, add ActiveAttr, then after some time something better comes, we again change the code, etc etc etc. Can you give it some thinking and maybe play with it a bit?

**Comment by ryansch** [comment]
I was wondering the same thing.  Honestly the contract we have with the model is pretty thin so making this pluggable would be pretty easy.

**Comment by ryansch** [comment]
I've paired this down to just the active_attr stuff.  I'll try to add the plugin architecture in the next couple weeks.

**Comment by karmi** [comment]
That would be awesome! Take your time and please ping me whenever you'd like to get some feedback or ping-pong something.

**Comment by ryansch** [comment]
Just FYI, I haven't forgotten about this.

**Comment by karmi** [comment]
@ryansch, that's great to hear :) Take your time!

**Comment by gmile** [comment]
@ryansch it looks like original author of `virtus` himself is abandoning the project. So virtus issues you're seeing are unlikely to be ever resolved, unless someone takes over the project. Yet even in that case I doubt virtus will remain a good choise, for reasons he well explained in [this thread](https://www.reddit.com/r/ruby/comments/3sjb24/virtus_to_be_abandoned_by_its_creator/) on reddit.

**Comment by ryansch** [comment]
I think I'd still like to add a pluggable interface so you can use whatever you want.  :-)

We'll just have to decide what the default is.

**Comment by gmile** [comment]
> by the author's own admission dry-data isn't production ready yet

@ryansch you're right.

I'm just thinking outloud. For me ActiveAttr depends on both `activemodel` and `activesupport `, and I'm a little biased towards both (those dependencies feel a bit too heavy for task).

**Comment by karmi** [comment]
> I think I'd still like to add a pluggable interface so you can use whatever you want. :-)

+++ :)

(It's just a question how _much_ benefit would be in abstracting everything away like that...)

**Comment by estolfo** [comment]
I'm going to close this, as it's no longer relevant with the removal of Elasticsearch::Persistence::Model.

**Comment by ryansch** [comment]
🎉

**Pull request closed without merging**
