### PR TITLE
Cache results mapping inside Results

### PR DESCRIPTION
**Pull request by RmMsr**
Seems to be the intention of the assignment.

### CODE REVIEW

**Comment by jeebster** [comment]
+1, I do need to reference ```Elasticsearch::Model::Response#results``` and ```Elasticsearch::Model::Response#records``` multiple times and can confirm a request is sent everytime these methods are called. It would be great to cache these!

**Comment by karmi** [comment]
Hi, this is weird -- can you provide more details?

Because as soon as you call `response.response`, you'll get back a final response object, which is [memoized](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/response.rb#L29-L33).

I think the assignment is simply wrong on that line. For one, I try to stay away from memoization whenever possible, second, the object _should_ be already memoized.

@jeebster I tried it in the `activerecord_article.rb` example and the search is not fired when you repeatedly access records or results:

```
> response = Article.search 'foo';
> response.records.to_a
2015-04-11 10:07:25 +0200: GET http://localhost:9200/articles/article/_search?q=foo [status:200, request:0.005s, query:0.002s]
2015-04-11 10:07:25 +0200: < {"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":2,"max_score":0.10848885,"hits":[{"_index":"articles","_type":"article","_id":"3","_score":0.10848885,"_source":{"title":"Foo Foo","published_at":null,"created_at":"2015-04-11T08:05:46.375Z","updated_at":"2015-04-11T08:05:46.375Z"}},{"_index":"articles","_type":"article","_id":"1","_score":0.076713204,"_source":{"title":"Foo","published_at":null,"created_at":"2015-04-11T08:05:46.367Z","updated_at":"2015-04-11T08:05:46.367Z"}}]}}
  Article Load (0.1ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (3, 1)
=> [#<Article:0x007f901b91db80
  id: 3,
  title: "Foo Foo",
  published_at: nil,
  created_at: 2015-04-11 08:05:46 UTC,
  updated_at: 2015-04-11 08:05:46 UTC>,
 #<Article:0x007f901b91dec8
  id: 1,
  title: "Foo",
  published_at: nil,
  created_at: 2015-04-11 08:05:46 UTC,
  updated_at: 2015-04-11 08:05:46 UTC>]
> response.records.to_a
  Article Load (0.1ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (3, 1)
=> [#<Article:0x007f901d14f988
  id: 3,
  title: "Foo Foo",
  published_at: nil,
  created_at: 2015-04-11 08:05:46 UTC,
  updated_at: 2015-04-11 08:05:46 UTC>,
 #<Article:0x007f901d1547a8
  id: 1,
  title: "Foo",
  published_at: nil,
  created_at: 2015-04-11 08:05:46 UTC,
  updated_at: 2015-04-11 08:05:46 UTC>]
> response.results.to_a
=> [#<Elasticsearch::Model::Response::Result:0x007f901bd844a8
  @result=
   {"_index"=>"articles",
    "_type"=>"article",
    "_id"=>"3",
    "_score"=>0.10848885,
    "_source"=>
     {"title"=>"Foo Foo", "published_at"=>nil, "created_at"=>"2015-04-11T08:05:46.375Z", "updated_at"=>"2015-04-11T08:05:46.375Z"}}>,
 #<Elasticsearch::Model::Response::Result:0x007f901bd84430
  @result=
   {"_index"=>"articles",
    "_type"=>"article",
    "_id"=>"1",
    "_score"=>0.076713204,
    "_source"=>
     {"title"=>"Foo", "published_at"=>nil, "created_at"=>"2015-04-11T08:05:46.367Z", "updated_at"=>"2015-04-11T08:05:46.367Z"}}>]
> response.results.to_a
=> [#<Elasticsearch::Model::Response::Result:0x007f901d494d78
  @result=
   {"_index"=>"articles",
    "_type"=>"article",
    "_id"=>"3",
    "_score"=>0.10848885,
    "_source"=>
     {"title"=>"Foo Foo", "published_at"=>nil, "created_at"=>"2015-04-11T08:05:46.375Z", "updated_at"=>"2015-04-11T08:05:46.375Z"}}>,
 #<Elasticsearch::Model::Response::Result:0x007f901d494b48
  @result=
   {"_index"=>"articles",
    "_type"=>"article",
    "_id"=>"1",
    "_score"=>0.076713204,
    "_source"=>
     {"title"=>"Foo", "published_at"=>nil, "created_at"=>"2015-04-11T08:05:46.367Z", "updated_at"=>"2015-04-11T08:05:46.367Z"}}>]
> 
```

**Comment by karmi** [comment]
Hi guys, can I ask for more feedback on my last message and code example?

**Comment by karmi** [comment]
Hi, I've removed the assignment altogether, seems to more floow the intent.

Please reopen or open a new issue if you think there's a problem, especially if you see the search request being executed repeatedly, @jeebster!

**Pull request closed without merging**
