### PR TITLE
Comment out missed line. Fixes #357

### LINKED ISSUE #357: Error installing 3rd template
The scripts in install the first and second templates work fine for me. 

However, when running the third one I get this error: 

```ruby
See http://sidekiq.org' from "."
[master 93cfc0d] Added a Sidekiq indexer
 3 files changed, 45 insertions(+), 1 deletion(-)
 create mode 100644 app/workers/indexer.rb

 Controllers    Adding SearchController...
--------------------------------------------------------------------------------

      create    app/controllers/search_controller.rb
The template [https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/03-expert.rb] could not be loaded. Error: Could not find "/Users/jonathan/Desktop/searchapp/https:/raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/search_controller_test.rb" in any of your source paths. Your current source paths are: 
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0/lib/rails/generators/rails/app/templates
```

Any help fixing this is appreciated!

### PR DESCRIPTION
**Pull request by jonathansimmons**
- added comment to link 222 which is a the second argument of the get request on line 221

### CODE REVIEW

**Comment by karmi** [comment]
Ah, thanks for the catch! Can you please sign the [CLA](http://www.elasticsearch.org/contributor-agreement/) so I can merge it? I know it's a small change, but the signature is handy for any future contributions as well...

**Comment by karmi** [comment]
I've also updated all the URLs to raw content in 72f3c13, so thanks for the catch.

I'd like to add proper tests for these templates, so our CI can run the generation of example applications and intercept errors like these...

**Comment by jonathansimmons** [comment]
You're welcome!

**Comment by karmi** [comment]
URLs fixed in 72f3c1397da439365b7f91080586b29f1f7afc12

**Pull request closed without merging**
